-- SUPERSEDED — do not run this file.
--
-- Username login + user management moved to a single centralized version
-- in the Finance Dashboard repo, so there's one Users screen for every app
-- instead of a separate one per app (Thijs, 2026-08-09). Run this instead:
--
--   crossing-lodges-budget/add_username_login_and_app_access.sql
--
-- (crossing-lodges-budget is the Finance Dashboard app's repo, inside your
-- CL Dashboard folder.)
